-- Create Services Table if not exists
create table if not exists public.services (
  id bigint generated by default as identity primary key,
  salon_id bigint references public.salons on delete cascade not null,
  name text not null,
  price text,
  category text,
  duration_mins integer,
  created_at timestamp with time zone default timezone('utc'::text, now())
);
alter table public.services enable row level security;
create policy "Public view services" on services for select using (true);
create policy "Manager manage services" on services for all using (
  exists ( select 1 from salons where id = services.salon_id and owner_id = auth.uid() )
);

-- Create Stylists Table if not exists
create table if not exists public.stylists (
  id bigint generated by default as identity primary key,
  salon_id bigint references public.salons on delete cascade not null,
  name text not null,
  role text,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);
alter table public.stylists enable row level security;
create policy "Public view stylists" on stylists for select using (true);
create policy "Manager manage stylists" on stylists for all using (
  exists ( select 1 from salons where id = stylists.salon_id and owner_id = auth.uid() )
);

-- Create Salon Gallery Table if not exists
create table if not exists public.salon_gallery (
  id bigint generated by default as identity primary key,
  salon_id bigint references public.salons on delete cascade not null,
  image_url text not null,
  created_at timestamp with time zone default timezone('utc'::text, now())
);
alter table public.salon_gallery enable row level security;
create policy "Public view gallery" on salon_gallery for select using (true);
create policy "Manager manage gallery" on salon_gallery for all using (
  exists ( select 1 from salons where id = salon_gallery.salon_id and owner_id = auth.uid() )
);

-- Create Bookings Table if not exists
create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  salon_id bigint references public.salons on delete cascade not null,
  user_id uuid references auth.users not null,
  service_name text,
  status text default 'Pending',
  date text,
  time text,
  total_price text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);
alter table public.bookings enable row level security;
create policy "Public insert bookings" on bookings for insert with check ( auth.uid() = user_id );
create policy "Users view own bookings" on bookings for select using ( auth.uid() = user_id );
create policy "Manager view bookings" on bookings for select using (
  exists ( select 1 from salons where id = bookings.salon_id and owner_id = auth.uid() )
);
create policy "Manager update bookings" on bookings for update using (
  exists ( select 1 from salons where id = bookings.salon_id and owner_id = auth.uid() )
);

-- Create Notifications Table
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text not null,
  message text,
  type text,
  is_unread boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now())
);
alter table public.notifications enable row level security;
create policy "Users view own notifications" on public.notifications for select using ( auth.uid() = user_id );
create policy "Users update own notifications" on public.notifications for update using ( auth.uid() = user_id );
create policy "Users delete own notifications" on public.notifications for delete using ( auth.uid() = user_id );

-- Create Offers (Promotions) Table
create table if not exists public.salon_offers (
  id bigint generated by default as identity primary key,
  salon_id bigint references public.salons on delete cascade not null,
  title text not null,
  discount text,
  expires text,
  status text default 'Active',
  created_at timestamp with time zone default timezone('utc'::text, now())
);
alter table public.salon_offers enable row level security;
create policy "Public view offers" on public.salon_offers for select using (true);
create policy "Manager manage offers" on public.salon_offers for all using (
  exists ( select 1 from salons where id = salon_offers.salon_id and owner_id = auth.uid() )
);

-- Ensure Salons has necessary columns
alter table public.salons add column if not exists banner_url text;
alter table public.salons add column if not exists is_open boolean default true;
alter table public.salons add column if not exists phone text;
alter table public.salons add column if not exists rating numeric default 0;
alter table public.salons add column if not exists review_count integer default 0;
alter table public.salons add column if not exists payout_method_1 text;
alter table public.salons add column if not exists payout_number_1 text;
alter table public.salons add column if not exists payout_method_2 text;
alter table public.salons add column if not exists payout_number_2 text;
alter table public.salons add column if not exists email text;
