-- CHECK: Profiles Table
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  full_name text,
  role text default 'client',
  avatar_url text,
  updated_at timestamp with time zone
);

alter table public.profiles enable row level security;
create policy "Public profiles are viewable by everyone." on profiles for select using ( true );
create policy "Users can insert their own profile." on profiles for insert with check ( auth.uid() = id );
create policy "Users can update own profile." on profiles for update using ( auth.uid() = id );

-- CHECK: Salons Table
create table if not exists public.salons (
  id bigint generated by default as identity primary key,
  owner_id uuid references auth.users on delete cascade not null,
  name text,
  address text,
  description text,
  banner_url text,
  status text default 'Closed',
  created_at timestamp with time zone default timezone('utc'::text, now())
);

alter table public.salons enable row level security;
create policy "Managers can insert their own salon." on salons for insert with check ( auth.uid() = owner_id );
create policy "Managers can update their own salon." on salons for update using ( auth.uid() = owner_id );
create policy "Salons are viewable by everyone." on salons for select using ( true );
